In [ ]:
import numpy

In [11]:
import numpy as mk

In [12]:
a=mk.array([(1,2,3),(4,5,6)])

In [13]:
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
b=mk.array([(4,5,6),(7,8,9)])

In [24]:
py=mk.transpose(a)

In [18]:
py1=mk.transpose(b)

In [25]:
print(py)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
print(py1)

[[4 7]
 [5 8]
 [6 9]]


In [26]:
py.ravel()

array([1, 4, 2, 5, 3, 6])

In [28]:
b.reshape(2,3)

array([[4, 5, 6],
       [7, 8, 9]])

In [42]:
ze=mk.zeros((3,3))

In [43]:
print(ze)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [44]:
one=mk.ones((2,6))

In [45]:
print(one)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [46]:
mk.append(a,b)

array([1, 2, 3, 4, 5, 6, 4, 5, 6, 7, 8, 9])

In [49]:
mk.append(a,(9,8,6))

array([1, 2, 3, 4, 5, 6, 9, 8, 6])

In [51]:
mk.insert(a,2,5)

array([1, 2, 5, 3, 4, 5, 6])

In [67]:
mk.delete(a,2)

array([1, 2, 4, 5, 6])

In [73]:
mk.delete(a,5)

array([1, 2, 3, 4, 5])

In [79]:
mk.random.random((5,5))

array([[0.91819639, 0.55279439, 0.64054105, 0.43585343, 0.48908109],
       [0.32212596, 0.97650898, 0.90886101, 0.37302218, 0.02916861],
       [0.96341087, 0.05271083, 0.36122173, 0.85322166, 0.56987951],
       [0.68577707, 0.24998319, 0.45889536, 0.62082317, 0.31243156],
       [0.92106604, 0.24626262, 0.90575937, 0.85494786, 0.86152311]])